/* $Revision: 1.1.1.1 $ */
/* XPM */
char * sw_off_xpm[] = {
"10 24 4 1",
" 	c #4D0FDB",
".	c #FFFFFF",
"+	c #000000",
"@	c #E0F909",
"          ",
"          ",
"          ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
"  ......  ",
" ++++++++ ",
" +@@@@@@+ ",
" ++++++++ ",
" +@@@@@@+ ",
" ++++++++ ",
" +@@@@@@+ ",
" ++++++++ ",
" +@@@@@@+ ",
" ++++++++ ",
"          ",
"          ",
"          "};
/* XPM */
char * sw_on_xpm[] = {
"10 24 4 1",
" 	c #4D0FDB",
".	c #000000",
"+	c #E0F909",
"@	c #FFFFFF",
"          ",
"          ",
"          ",
" ........ ",
" .++++++. ",
" ........ ",
" .++++++. ",
" ........ ",
" .++++++. ",
" ........ ",
" .++++++. ",
" ........ ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"  @@@@@@  ",
"          ",
"          ",
"          "};
/* XPM */
char * sw_test_pcb3_xpm[] = {
"147 36 165 2",
"  	c None",
". 	c #555452",
"+ 	c #1C1C1C",
"@ 	c #1F1F1E",
"# 	c #323230",
"$ 	c #B4B3AF",
"% 	c #A5A3A0",
"& 	c #242423",
"* 	c #353433",
"= 	c #C5C3BE",
"- 	c #3F3E3D",
"; 	c #111111",
"> 	c #000000",
", 	c #7A7976",
"' 	c #20201F",
") 	c #292928",
"! 	c #A7A6A2",
"~ 	c #5E5D5B",
"{ 	c #D2D0CB",
"] 	c #222121",
"^ 	c #CECCC8",
"/ 	c #D5D3CE",
"( 	c #545351",
"_ 	c #1B1B1A",
": 	c #232221",
"< 	c #8E8D8A",
"[ 	c #D3D1CD",
"} 	c #1A1A19",
"| 	c #0C0C0C",
"1 	c #9E9C99",
"2 	c #252524",
"3 	c #9F9D9A",
"4 	c #6E6D6B",
"5 	c #C1BFBB",
"6 	c #292827",
"7 	c #D9D7D2",
"8 	c #656462",
"9 	c #1D1D1C",
"0 	c #494947",
"a 	c #979692",
"b 	c #D7D5D0",
"c 	c #949390",
"d 	c #A1A09C",
"e 	c #6D6C69",
"f 	c #4D4C4A",
"g 	c #9D9C98",
"h 	c #C0BFBA",
"i 	c #CAC8C3",
"j 	c #DBD9D4",
"k 	c #A7A5A1",
"l 	c #191918",
"m 	c #ABA9A5",
"n 	c #484846",
"o 	c #666563",
"p 	c #CCCAC5",
"q 	c #767572",
"r 	c #585755",
"s 	c #131312",
"t 	c #AAA8A5",
"u 	c #141413",
"v 	c #2A2A29",
"w 	c #424240",
"x 	c #7E7D7A",
"y 	c #B2B0AC",
"z 	c #73726F",
"A 	c #D8D6D1",
"B 	c #B1AFAB",
"C 	c #C6C5C0",
"D 	c #090909",
"E 	c #D6D4CF",
"F 	c #101010",
"G 	c #C7C5C1",
"H 	c #BEBCB8",
"I 	c #747370",
"J 	c #52514F",
"K 	c #BFBDB9",
"L 	c #181817",
"M 	c #B3B2AE",
"N 	c #212020",
"O 	c #ACAAA6",
"P 	c #171717",
"Q 	c #C3C1BD",
"R 	c #A3A29E",
"S 	c #3A3938",
"T 	c #B5B4AF",
"U 	c #5A5957",
"V 	c #6F6E6C",
"W 	c #2F2F2E",
"X 	c #888784",
"Y 	c #6E6D6A",
"Z 	c #807F7C",
"` 	c #030303",
" .	c #161616",
"..	c #3E3E3C",
"+.	c #C0BEB9",
"@.	c #646361",
"#.	c #A09F9B",
"$.	c #232322",
"%.	c #A8A7A3",
"&.	c #1C1B1B",
"*.	c #575654",
"=.	c #0E0E0D",
"-.	c #CFCDC8",
";.	c #1E1E1D",
">.	c #A09E9B",
",.	c #686765",
"'.	c #0B0B0B",
").	c #B8B6B2",
"!.	c #D4D2CD",
"~.	c #72716E",
"{.	c #4F4F4D",
"].	c #30302F",
"^.	c #DAD8D3",
"/.	c #D1CFCA",
"(.	c #71706D",
"_.	c #50504E",
":.	c #777673",
"<.	c #7D7C79",
"[.	c #3C3C3A",
"}.	c #41403F",
"|.	c #8F8E8B",
"1.	c #8A8986",
"2.	c #2B2B2A",
"3.	c #CDCBC7",
"4.	c #969591",
"5.	c #D3D1CC",
"6.	c #020202",
"7.	c #787774",
"8.	c #121212",
"9.	c #050505",
"0.	c #0F0F0E",
"a.	c #C8C6C2",
"b.	c #D0CEC9",
"c.	c #070707",
"d.	c #151514",
"e.	c #4C4B4A",
"f.	c #878683",
"g.	c #282726",
"h.	c #CBC9C4",
"i.	c #484745",
"j.	c #676663",
"k.	c #4E4D4B",
"l.	c #C6C4BF",
"m.	c #8D8C89",
"n.	c #817F7C",
"o.	c #9A9996",
"p.	c #92908D",
"q.	c #393837",
"r.	c #0D0D0D",
"s.	c #010101",
"t.	c #535250",
"u.	c #A9A8A4",
"v.	c #9B9A96",
"w.	c #373735",
"x.	c #9C9B97",
"y.	c #42413F",
"z.	c #C2C0BC",
"A.	c #333231",
"B.	c #757472",
"C.	c #272626",
"D.	c #636260",
"E.	c #464544",
"F.	c #4D0FDB",
"G.	c #FFFFFF",
"H.	c #E0F909",
"                                                                                                                                                                                                                                                                                                      ",
". + @ # $     % & + * =                           - ; >               . + @ # $           , ' ' ) !               ~ >           { > ] ] ] ^           / ( _ : <         [ ] ] ] } |           1 2 @ 2 3           % & + * =             4 > 5           { > ] : 6 1           7 8 ' 9 0               ",
"a b   c :     _ d   e f                           g h >               a b   c :           i j   k l             m n >           { >                   o 0 7   p                 q r           s t   t u           _ d   e f             v w x           { >     y u           z n A   B               ",
"      C D   / > E   m F   G ' H   I J               { >                     C D                 % u           b # K >           { >                   L M                       N O           P t   t L         / > E   m F           Q _ R S           { >     t ;           9 T                     ",
"      o U     l R   V > b   d W k 6 [               { >                     o U             X 9 ; R           Y Z { >           { ` )  ...+.        A > @.' ' #.              k $.            %. .&.P %.          l R   V > b         Z *.b =.-.        { > ] ;.=.a         7 > b                     ",
"    X W [     >.@ ' @.> A     ,.'.).                { >                   X W [               !.~.{.        ).].^.{ >           ^./.  ^.z ].        b > (.  >.l               _.:.            ( Z [ <.(           >.@ ' @.> A         [.c   }.|.        { >   b <.0         A > b                     ",
"  1.2.3.            y l     j }._ 4.                { >                 1.2.3.                  5.6.7       7.8.] N > ] /.              p 9.          0.O   / > E           -.| a.          7 ` !.  [ ` 7               y l         b.c.' ] d.e.        { >     [ 6.7         + T                     ",
"f.g.h.        p   7 i.j.    q k.l.@ K               { >               f.g.h.              B     m.P               { >           C 5.  j :.#           0 (.  >.}             n.w             j ; o.  g 8.j         p   7 i.j.        p.q.    +.r.A       { >     k F j         (.0 A   M               ",
"s. .] ] q.    m.N _ t./   u.: /.  v.2.E           q.N > ] q           s. .] ] q.          w.;.&.2.t               { >           x.+ N l y.z.          5 A.+ $.R             v a               g : + $.>.          m.N _ t./         k.B.      ] d       { > ] ] C.g           7 D.@ ;.E.              ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.F.G.G.G.G.G.G.F.F.                    F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.      ",
"        F.> > > > > > > > F.                    F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.      ",
"        F.> H.H.H.H.H.H.> F.                    F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.      ",
"        F.> > > > > > > > F.                    F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.      ",
"        F.> H.H.H.H.H.H.> F.                    F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.      ",
"        F.> > > > > > > > F.                    F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.      ",
"        F.> H.H.H.H.H.H.> F.                    F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.      ",
"        F.> > > > > > > > F.                    F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.      ",
"        F.> H.H.H.H.H.H.> F.                    F.> H.H.H.H.H.H.> F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> H.H.H.H.H.H.> F.      ",
"        F.> > > > > > > > F.                    F.> > > > > > > > F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.F.F.G.G.G.G.G.G.F.F.F.F.G.G.G.G.G.G.F.F.F.> > > > > > > > F.      ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"        F.F.F.F.F.F.F.F.F.F.                    F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.      ",
"                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                      "};
/* XPM */
char * sw_test_willem_xpm[] = {
"147 36 164 2",
"  	c None",
". 	c #1C1C1C",
"+ 	c #1F1F1E",
"@ 	c #323230",
"# 	c #B4B3AF",
"$ 	c #A5A3A0",
"% 	c #242423",
"& 	c #353433",
"* 	c #C5C3BE",
"= 	c #D9D7D2",
"- 	c #656462",
"; 	c #20201F",
"> 	c #1D1D1C",
", 	c #494947",
"' 	c #D2D0CB",
") 	c #000000",
"! 	c #222121",
"~ 	c #232221",
"{ 	c #292827",
"] 	c #9E9C99",
"^ 	c #6E6D6B",
"/ 	c #C1BFBB",
"( 	c #252524",
"_ 	c #9F9D9A",
": 	c #D3D1CD",
"< 	c #1A1A19",
"[ 	c #0C0C0C",
"} 	c #D5D3CE",
"| 	c #545351",
"1 	c #1B1B1A",
"2 	c #8E8D8A",
"3 	c #CECCC8",
"4 	c #5E5D5B",
"5 	c #7A7976",
"6 	c #292928",
"7 	c #A7A6A2",
"8 	c #3F3E3D",
"9 	c #111111",
"0 	c #979692",
"a 	c #D7D5D0",
"b 	c #949390",
"c 	c #A1A09C",
"d 	c #6D6C69",
"e 	c #4D4C4A",
"f 	c #73726F",
"g 	c #484846",
"h 	c #D8D6D1",
"i 	c #B1AFAB",
"j 	c #B2B0AC",
"k 	c #141413",
"l 	c #2A2A29",
"m 	c #424240",
"n 	c #7E7D7A",
"o 	c #131312",
"p 	c #AAA8A5",
"q 	c #767572",
"r 	c #585755",
"s 	c #666563",
"t 	c #CCCAC5",
"u 	c #ABA9A5",
"v 	c #CAC8C3",
"w 	c #DBD9D4",
"x 	c #A7A5A1",
"y 	c #191918",
"z 	c #9D9C98",
"A 	c #C0BFBA",
"B 	c #C6C5C0",
"C 	c #090909",
"D 	c #D6D4CF",
"E 	c #101010",
"F 	c #C7C5C1",
"G 	c #BEBCB8",
"H 	c #747370",
"I 	c #52514F",
"J 	c #B5B4AF",
"K 	c #C3C1BD",
"L 	c #A3A29E",
"M 	c #3A3938",
"N 	c #171717",
"O 	c #181817",
"P 	c #212020",
"Q 	c #ACAAA6",
"R 	c #B3B2AE",
"S 	c #BFBDB9",
"T 	c #5A5957",
"U 	c #6F6E6C",
"V 	c #2F2F2E",
"W 	c #1E1E1D",
"X 	c #0E0E0D",
"Y 	c #807F7C",
"Z 	c #575654",
"` 	c #CFCDC8",
" .	c #A8A7A3",
"..	c #161616",
"+.	c #1C1B1B",
"@.	c #232322",
"#.	c #646361",
"$.	c #A09F9B",
"%.	c #030303",
"&.	c #3E3E3C",
"*.	c #C0BEB9",
"=.	c #6E6D6A",
"-.	c #888784",
";.	c #A09E9B",
">.	c #686765",
",.	c #0B0B0B",
"'.	c #B8B6B2",
").	c #7D7C79",
"!.	c #3C3C3A",
"~.	c #41403F",
"{.	c #8F8E8B",
"].	c #50504E",
"^.	c #777673",
"/.	c #71706D",
"(.	c #DAD8D3",
"_.	c #D1CFCA",
":.	c #30302F",
"<.	c #D4D2CD",
"[.	c #72716E",
"}.	c #4F4F4D",
"|.	c #8A8986",
"1.	c #2B2B2A",
"2.	c #CDCBC7",
"3.	c #969591",
"4.	c #020202",
"5.	c #D0CEC9",
"6.	c #070707",
"7.	c #151514",
"8.	c #4C4B4A",
"9.	c #C8C6C2",
"0.	c #0F0F0E",
"a.	c #050505",
"b.	c #787774",
"c.	c #121212",
"d.	c #D3D1CC",
"e.	c #878683",
"f.	c #282726",
"g.	c #CBC9C4",
"h.	c #484745",
"i.	c #676663",
"j.	c #4E4D4B",
"k.	c #C6C4BF",
"l.	c #92908D",
"m.	c #393837",
"n.	c #0D0D0D",
"o.	c #9A9996",
"p.	c #817F7C",
"q.	c #8D8C89",
"r.	c #010101",
"s.	c #535250",
"t.	c #A9A8A4",
"u.	c #9B9A96",
"v.	c #636260",
"w.	c #464544",
"x.	c #272626",
"y.	c #757472",
"z.	c #333231",
"A.	c #9C9B97",
"B.	c #42413F",
"C.	c #C2C0BC",
"D.	c #373735",
"E.	c #4D0FDB",
"F.	c #FFFFFF",
"G.	c #E0F909",
"                                                                                                                                                                                                                                                                                                      ",
"  . + @ #     $ % . & *                           = - ; > ,         ' ) ! ~ { ]             ^ ) /             $ % . & *           ] ( + ( _         : ! ! ! < [           } | 1 ~ 2         ' ) ! ! ! 3               4 )             5 ; ; 6 7             . + @ #           8 9 )                   ",
"0 a   b ~     1 c   d e                           f g h   i         ' )     j k             l m n             1 c   d e           o p   p k                 q r           s , =   t         ' )                     u g )             v w   x y           0 a   b ~           z A )                   ",
"      B C   } ) D   u E   F ; G   H I             > J               ' )     p 9           K 1 L M           } ) D   u E           N p   p O                 P Q           O R               ' )                   a @ S )                   $ k                 B C             ' )                   ",
"      s T     y L   U ) a   c V x { :           = ) a               ' ) ! W X 0           Y Z a X `           y L   U ) a          ...+.N  .              x @.          h ) #.; ; $.        ' %.6 ..&.*.          =.Y ' )               -.> 9 L                 s T             ' )                   ",
"    -.V :     ;.+ ; #.) h     >.,.'.            h ) a               ' )   a ).,           !.b   ~.{.          ;.+ ; #.) h         | Y : ).|               ].^.          a ) /.  ;.y         (._.  (.f :.        '.:.(.' )                 <.[.}.              -.V :             ' )                   ",
"  |.1.2.            j y     w ~.1 3.              . J               ' )     : 4.=       5.6.; ! 7.8.                j y         = %.<.  : %.=           ` [ 9.            0.Q   } ) D               t a.        b.c.! P ) ! _.              d.4.=           |.1.2.              ' )                   ",
"e.f.g.        t   = h.i.    q j.k.+ S             /., h   R         ' )     x E w       l.m.    *.n.h         t   = h.i.        w 9 o.  z c.w           p.m               , /.  ;.<         B d.  w ^.@               ' )             i     q.N           e.f.g.                ' )                   ",
"r...! ! m.    q.P 1 s.}   t.~ _.  u.1.D           = v.+ W w.        ' ) ! ! x.z         j.y.      ! c         q.P 1 s.}           z ~ . @.;.            l 0               / z.. @.L         A.. P y B.C.              ' )             D.W +.1.p           r...! ! m.          m.P ) ! q               ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.      ",
"        E.E.F.F.F.F.F.F.E.E.                    E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.      ",
"        E.) ) ) ) ) ) ) ) E.                    E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) G.G.G.G.G.G.) E.                    E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) ) ) ) ) ) ) ) E.                    E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) G.G.G.G.G.G.) E.                    E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) ) ) ) ) ) ) ) E.                    E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) G.G.G.G.G.G.) E.                    E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) ) ) ) ) ) ) ) E.                    E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) G.G.G.G.G.G.) E.                    E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.) G.G.G.G.G.G.) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.) ) ) ) ) ) ) ) E.                    E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.) ) ) ) ) ) ) ) E.E.E.F.F.F.F.F.F.E.E.E.E.F.F.F.F.F.F.E.E.      ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"        E.E.E.E.E.E.E.E.E.E.                    E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.      ",
"                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                      "};
